name: Vale Lint

on:
  push:
    paths:
      - 'test-vale/**'
  pull_request:
    paths:
      - 'test-vale/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: 'test-vale/**'

      - name: Run Vale
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: errata-ai/vale-action@reviewdog
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          version: 3.9.4
          fail_on_error: true
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
