name: Vale Lint

on:
  push:
    paths:
      - 'test-vale/**'
  pull_request:
    paths:
      - 'test-vale/**'

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: test-vale
          version: 3.9.4
          fail_on_error: true
          filter_mode: diff_context
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
